### ISSUE TITLE
Add Activity Interactions Component

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/example-ts#10]
## Issue 
Pieces for Developers utilizes a "Workflow Activity View" that shows all of the interactions, references, creation events, and more that take place across all of your products. Showing this functionality can be helpful in understanding the different touch points that are stored locally on your device to help your experience improve.

## TODO

- [ ] Successfully print your entire workflow activity stream 
- [ ] Create a functional location to display this information (or) Create a new view to host workflow activity 
- [ ] Add slight documentation around your process

**Comment by pythonistical** [comment]
Hi @jordan-pieces can you assign me to this issue?

**Comment by jordan-pieces** [comment]
@pythonistical absolutely - I think this is a great place to start but may be interesting as this is a whole new view. I also see that you have requested to be assigned issue #3 that was previously assigned to another user. would you like to prioritize this issue or or #3 for now ? 

Currently just focusing on one issue (until completed) at a time is ideal, until we have more consistent contributions from specific users. Let me know what you are thinking and which issue you would like to start with - that way you can get going! :)

**Comment by pythonistical** [comment]
i will first work with #3 for now

**Comment by RohanMishra315** [comment]
Hey @jordan-pieces If no one is working on it, should I take it ?

**Comment by agrim0312** [comment]
hey @jordan-pieces can i work on this if no one is working on it.

**Comment by jordan-pieces** [comment]
hello all, i wanted to check in with the three of you, we have a few updates coming tonight and in the AM, but wanted to see if you all three are still interested in working on this endpoint! 👍 

let me know and i can respond to you soon and we can split this up or get this assigned to someone soon @agrim0312 @RohanMishra315  @pythonistical

**Comment by pythonistical** [comment]
@jordan-pieces I think I am not going to work on this issue because I got assigned to #42 first, so this can got to @agrim0312 or @RohanMishra315

**Comment by agrim0312** [comment]
@jordan-pieces I am still intrested in working on this endpoint and can contibute collectively with @RohanMishra315.

**Comment by RohanMishra315** [comment]
It  will be great to work with you @agrim0312 .

**Comment by jordan-pieces** [comment]
okay @agrim0312 why dont you go ahead and head this up, would love to see the collaboration between you two take place here on this issue as you are working through this 👍 

i am going to assign the windows support issue to you @RohanMishra315 to lead that issue and collaborate with others where needed while supporting @agrim0312 

let me know if you have any questions or assistance 💯

**Comment by agrim0312** [comment]
@jordan-pieces I saw pieces desktop app workflow activity, However i am not able to figure out that, is there any particular endpoint from where i can fetch the workflow activity of the user. @RohanMishra315 do you know ??

**Comment by RohanMishra315** [comment]
hey @agrim0312  to fetch the workflow activity of a user , I think you can use the `/activities` endpoint provided by the Pieces API. This endpoint allows you to retrieve a list of activities for a specific user.

**Comment by agrim0312** [comment]
thanks, @RohanMishra315  👍

**Comment by agrim0312** [comment]
@jordan-pieces i have changed layout for displaying the workflow.

![image](https://github.com/pieces-app/example-ts/assets/97701696/8f2ca146-9282-4325-b004-620c70e75765)

is it looking good or shall i change the component location to somewhere else.

**Comment by jordan-pieces** [comment]
@agrim0312 this is looking fantastic! if you want to get a PR opened and attach it to this issue that would be fantastic and i can take a deeper look (if you are feeling good about the functionality of the activities endpoint). If possible recording a GIF here would be useful for others in the future to see how the `/activities` endpoint works and what the outcome of its usage is. 👍

**Comment by RohanMishra315** [comment]
Nice work @agrim0312

**Comment by agrim0312** [comment]
sure @jordan-pieces, after completing it i will surely open a PR and put a GIF here for future references. :+1: 
thanks @RohanMishra315 :+1:

**Comment by jordan-pieces** [comment]
@RohanMishra315 awesome thank you for spending time on this together and really looking forward to seeing some of the activity endpoints on display 👍

**Comment by jordan-pieces** [comment]
@agrim0312 just wanted to check in on your work with the activity endpoint - hope its going well and let me (or anyone on the team) know if you need anything from us

**Comment by agrim0312** [comment]
@jordan-pieces how's is this looking??
![image](https://github.com/pieces-app/example-ts/assets/97701696/6a3ea47f-4035-4652-96ed-fdf6adbd04a7)

**Comment by jordan-pieces** [comment]
@agrim0312 this is looking great! 😌 excited to check out the PR
